spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./db_bookmarks;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2
